name: Keep HuggingFace Alive

on:
  schedule:
    # يشتغل تلقائياً كل 10 دقائق
    - cron: '*/10 * * * *'
  workflow_dispatch: # زر للتشغيل اليدوي للتجربة

jobs:
  ping_job:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping
        run: |
          curl -s -L "https://ayman001jihad-jstta.hf.spacegithub/workflows/ping.yml" > /dev/null
          echo "تم إرسال الإشارة بنجاح!"
